#! /bin/sh

IFS=':'

APROPSED=/usr/wiss/slind/hol/working/tools/Xhelp/h_apro.sed
DEFHOLHELPPATH=:/usr/wiss/slind/hol/working/help/90:/usr/wiss/slind/hol/working/help/88/ENTRIES
CUR_HELP_PATH=`echo ${2} ${HOL_HELP_PATH} ${DEFHOLHELPPATH} |sed 's/ /:/g'`

for i in $CUR_HELP_PATH
do
	for j in $i/*${1}*doc
	do
	if test -f $j
	then
		sed -f  $APROPSED $j
		echo ""
	fi
	done
done

echo "end of search"
echo ""


