#! /bin/sh

IFS=':'

THMSED=/usr/wiss/slind/hol/working/tools/Xhelp/h_thm.sed
DEFTHMHELPPATH=:/usr/wiss/slind/hol/working/help/88/THEOREMS/*
CUR_HELP_PATH=`echo ${2} ${THM_HELP_PATH} ${DEFTHMHELPPATH} |sed 's/ /:/g'`


for i in $CUR_HELP_PATH
do
	for j in $i/*${1}*doc
	do
	if test -f $j
	then
		sed -f $THMSED $j
		echo ""
	fi
	done
done




