#! /bin/sh

IFS=':'

DEFHOLHELPPATH=:/usr/wiss/slind/hol/working/help/90:/usr/wiss/slind/hol/working/help/88/ENTRIES
CUR_HELP_PATH=`echo ${1} ${HOL_HELP_PATH} ${DEFHOLHELPPATH} | sed 's/ /:/g'`

for i in ${CUR_HELP_PATH}
do
	for j in $i/*.doc 
	do
	        echo $j 
		echo ""
        done
done

echo "end of search"
echo ""
