#!/bin/sh
#Creates symbolic links to the example files.
ln -s ../../contrib/orsml/examples/ex1.sml
ln -s ../../contrib/orsml/doc/manual.dvi
ln -s ../../contrib/orsml/doc/manual.ps
ln -s ../../contrib/orsml/examples/test.sml
