#!/bin/sh

# Declare library

echo 'Library.new_library'\
     '{name = "retrieve",'\
     ' doc = "Theorem Retrieval Library, by R.J.Boulton, ported by D.R.Syme",'\
     ' path = (!HOLdir) ^ "library/retrieve/",'\
     ' parents = [hol_lib],'\
     ' theories = [],'\
     ' code = ["exceptions.sig","exceptions.sml",'\
     '         "sets.sig","sets.sml",'\
     '         "extract.sig","extract.sml",'\
     '         "struct.sig","struct.sml",'\
     '         "name.sig","name.sml",'\
     '         "matching.sig","matching.sml",'\
     '         "sidecond.sig","sidecond.sml",'\
     '         "search.sig","search.sml",'\
     '         "user.sig","user.sml",'\
     '         "retrieve.sml"],'\
     ' help = ["entries/"],'\
     ' loaded = "fn () => ()"};'\
     | $1

mv retrieve.hol_lib ../desc
