#!/bin/sh
#Creates symbolic links to the example directories.
ln -s ../library/abs_theory/example abs_theory
ln -s ../contrib/bmark/src bmark
ln -s ../library/ind_def/examples inductive_def
ln -s ../library/prog_logic/examples prog_logic
ln -s ../library/unity/examples unity
ln -s ../library/window/Demo window_inference
ln -s ../library/decision decision
ln -s ../library/tfl/examples tfl
(cd orsml; make_links)
