#!/bin/sh

# make_cambridge_hol [-b|-o|-n]
# This builds hol in cambridge: the version of sml used and the 
# full directory path to the hol90.7 directory is hardwired in
# The other options are as for make_hol

make_hol sml -d /usr/groups/hol/hol90.7/ $*
