#!/bin/sh

echo "=====> Making system libraries"

# Libraries

(echo "Making the string library"; \
 cd ../library/string; make_string $1; \
 echo "The string library is made")

(echo "Making the set library"; \
 cd ../library/set; make_set $1; \
 echo "The set library is made")

(echo "Making the pred_set library"; \
 cd ../library/pred_set; make_pred_set $1; \
 echo "The pred_set library is made")

(echo "Making the group library"; \
 cd ../library/group; make_group $1; \
 echo "The group library is made")

(echo "Making the integer library"; \
 cd ../library/integer; make_integer $1; \
 echo "The integer library is made")

(echo "Making the unity library"; \
 cd ../library/unity; make_unity $1; \
 echo "The unity library is made")

(echo "Making the prog_logic library"; \
 cd ../library/prog_logic; make_prog_logic $1; \
 echo "The prog_logic library is made")

(echo "Making the pair library"; \
 cd ../library/pair; make_pair $1 ; \
 echo "The pair library is made")

(echo "Making the real library"; \
 cd ../library/real; make_real $1; \
 echo "The real library is made")

(echo "Making the wellorder library"; \
 cd ../library/wellorder; make_wellorder $1; \
 echo "The wellorder library is made")

(echo "Making the window library"; \
 cd ../library/window; make_window $1; \
 echo "The window library is made")

(echo "Making the list library"; \
 cd ../library/list; make_list $1; \
 echo "The list library is made")


(echo "Making the restricted quantifier library"; \
cd ../library/res_quan; make_res_quan $1; \
echo "The restricted quantifier library is made")

(echo "Making the word library"; \
 cd ../library/word; make_word $1; \
 echo "The word library is made")
