#!/bin/sh

echo "=====> Making contrib libraries"

# Clean the description directory out

(cd ../contrib/desc; /bin/rm *)
echo "=====> expunged old descriptions"



# Contrib entries

(cd ../contrib/automata; make_automata $1)
echo "=====> made automata"

(cd ../contrib/mutrec; make_mutrec $1)
echo "=====> made mutrec"

(cd ../contrib/nested_rec; make_nested_rec $1)
echo "=====> made nested_rec"

(cd ../contrib/bmark; make_bmark $1)
echo "=====> made bmark"

(cd ../contrib/assoc_comm; make_assoc_comm $1)
echo "=====> made assoc_comm"

(cd ../contrib/knuth_bendix; make_knuth_bendix $1)
echo "=====> made knuth_bendix"

(cd ../contrib/fixpoint; make_fixpoint $1)
echo "=====> made fixpoint"

(cd ../contrib/CSP; make_CSP $1)
echo "=====> made CSP"

(cd ../contrib/orsml; make_orsml $1)
echo "=====> made orsml"

(cd ../contrib/cond; make_cond $1)
echo "=====> made cond"

(cd ../contrib/more_utils; make_more_utils $1)
echo "=====> made more_utils"

(cd ../contrib/generator; make_generator $1)
echo "=====> made generator"

(cd ../contrib/pev_rewrite; make_pev_rewrite $1)
echo "=====> made pev_rewrite"

(cd ../contrib/part_fun; make_part_fun $1)
echo "=====> made part_fun"

(cd ../contrib/holML; make_holML $1)
echo "=====> made holML"


# find all declared contrib libraries:
#
#mapfilter find_library
#   ["automata", "mutrec", "nested_rec", "bmark", "assoc_comm", "knuth_bendix",
#    "fixpoint", "CSP", "orsml", "cond", "more_utils", "generator", 
#    "pev_rewrite", "part_fun", "holML"];
#
