#!/bin/sh

# Make script for holML library

# Build the theories


$* < theories/src/more_list/mk_more_list.sml
$* < theories/src/more_string/mk_more_string.sml
$* < theories/src/finmap/mk_finmap.sml
$* < theories/src/Core/Common/mk_common_holML_core.sml
$* < theories/src/Core/Plain_Core/mk_holML_Plain_Core.sml
$* < theories/src/Core/Determinacy/mk_core_determinacy.sml
$* < theories/src/Modules/Common/mk_common_ModML.sml
$* < theories/src/Modules/ModML/mk_ModML.sml
$* < theories/src/Modules/HOFML/mk_HOFML.sml

# Install the library description file

$* < theories/src/mk_holML_lib.sml

mv holML.hol_lib ../desc
