#!/bin/sh

# Declare library

echo 'new_library'\
     '{name = "cond",'\
     'doc = "Proof support for conditional expressions, by R. Reetz",'\
     'path = (!HOLdir)^"contrib/cond/",'\
     'parents = [],'\
     'theories = [],'\
     'code = ["cond.sig", "cond.sml"],'\
     'help = [],'\
     'loaded = "fn () => ()"};'\
     | $1

mv cond.hol_lib ../desc
