#!/bin/sh

echo 'new_library {'\
     'name = "pev_rewrite",'\
     'doc = "A generator for efficient rewriting functions, by Morten Welinder",'\
     'path = (!HOLdir)^"contrib/pev_rewrite/",'\
     'parents = []',\
     'theories = [],'\
     'code = ["convgen.sml"],'\
     'help = [],'\
     'loaded = "fn () => ()"};'\
     | $1

mv pev_rewrite.hol_lib ../desc
