#!/bin/sh
#
# Determine architecture and OS
#
case `uname -s` in
     HP-UX) ARCH=hppa;;
     SunOS) ARCH=`arch`
            case `uname -r` in
                 4*) case $ARCH in
                          sun4) ARCH=sparc-sunos;;
                          *) ;;
                     esac;;
                 5*) case $ARCH in
                          sun4) ARCH="sparc-solaris";;
                          i?86*) ARCH="x86-solaris";;
                          *) ;;
                     esac;;
                 *) ;;
            esac;;
     Linux) ARCH=`arch`
            case $ARCH in
                 i?86*) ARCH="x86-linux";;
                 *) ;;
            esac;;
     *) ARCH=`arch`;;
esac
echo $ARCH
