#!/bin/sh

# Build theories

$1 < theories/src/mk_lift.sml
$1 < theories/src/mk_part_fun.sml
$1 < theories/src/mk_finfun.sml

# Declare library

$1 < theories/src/mk_part_fun_lib.sml

mv part_fun.hol_lib ../desc
