#!/bin/sh

# Declare library

echo 'new_library'\
     '{name = "assoc_comm",'\
     'doc = "Associative-commutative unification, matching, and rewriting, by K. Slind",'\
     'path = (!HOLdir)^"contrib/assoc_comm/",'\
     'parents = [],'\
     'theories = [],'\
     'code = ["lib.sml", "term.sml", "subst.sml",'\
     '        "polynomial.sml", "acu.sml", "tools.sml"],'\
     'help = [],'\
     'loaded = "fn () => Lib.use_string\"Ac_tools.Acu.Ac_term.install_ac_pp()\""};'\
     | $1

mv assoc_comm.hol_lib ../desc
