#!/bin/sh

# Declare library

echo 'new_library'\
     '{name = "more_utils",'\
     'doc = "Additional proof support, by R. Reetz",'\
     'path = (!HOLdir)^"contrib/more_utils/",'\
     'parents = [],'\
     'theories = [],'\
     'code = ["more_utils.sig", "more_utils.sml",'\
     '        "benchmark.sig", "benchmark.sml"],'\
     'help = [],'\
     'loaded = "fn () => ()"};'\
     | $1

mv more_utils.hol_lib ../desc
