#!/bin/sh

echo 'new_library {'\
     'name = "knuth_bendix",'\
     'doc = "Knuth-Bendix completion, author Konrad Slind",'\
     'path = (!HOLdir)^"contrib/knuth_bendix/",'\
     'parents = []',\
     'theories = [],'\
     'code = ["kb_lib.sig","kb_lib.sml",'\
     '        "kb_rewrite.sig","kb_rewrite.sml",'\
     '        "kb.sig", "kb.sml", "kb_order.sig","kb_order.sml"],'\
     'help = [],'\
     'loaded = "fn () => ()"};'\
     | $1

mv knuth_bendix.hol_lib ../desc
