#!/bin/sh
#
# A generalization of the previous version, from Matthew Morley (although
# I changed the order of the arguments from his version).
#
# $1 -- where to get original binary image
# $2 -- where to dump created binary image
# $3 -- HOL root directory
# 
echo Install.install\"$3\"\;save_hol\"$2\"\; | $1
