#!/bin/sh

echo 'new_library {'\
     'name = "bmark",'\
     'doc = "HOL benchmark (a multiplier circuit), author Mike Gordon",'\
     'path = (!HOLdir)^"contrib/bmark/",'\
     'parents = [unwind_lib]',\
     'theories = [],'\
     'code = ["run.sml"],'\
     'help = [],'\
     'loaded = "fn () => ()"};'\
     | $1

mv bmark.hol_lib ../desc
