#!/bin/sh

# Declare library

echo 'new_library'\
     '{name = "mutrec",'\
     'doc = "Mutually recursive type definition library, by E. Gunter",'\
     'path = (!HOLdir)^"contrib/mutrec/",'\
     'parents = [hol_lib, utils_lib, num_lib],'\
     'theories = [],'\
     'code = ["type_info.sml", '\
             '"mut_rec_type_input.sig", '\
             '"mut_rec_ty.sig", "mut_rec_ty.sml", '\
             '"recftn.sml", '\
             '"cons_thms.sig", "cons_thms.sml", '\
             '"total_mut_rec_type_def.sml"],'\
     'help = [],'\
     'loaded = "fn () => ()"};'\
     | $1

mv mutrec.hol_lib ../desc
