#!/bin/sh

echo 'new_library {'\
     'name = "BoyerMoore",'\
     'doc = "Automation ala Boyer-Moore, author Richard Boulton",'\
     'path = (!HOLdir)^"contrib/BoyerMoore/",'\
     'parents = [num_lib]',\
     'theories = [],'\
     'code = ["support.sml","struct_equal.sml", "shells.sml",'\
             '"environment.sml", "clausal_form.sml", "waterfall.sml",'\
             '"rewrite_rules.sml","definitions.sml", "terms_and_clauses.sml",'\
             '"equalities.sml", "generalize.sml", "irrelevance.sml",'\
             '"induction.sml", "main.sml"],'\
     'help = [],'\
     'loaded = "fn () => ()"};'\
     | $1

mv BoyerMoore.hol_lib ../desc
